pub const KillData = struct {
    match_id: []const u8,
    server_id: []const u8,
    server_name: []const u8,
    game_mode: []const u8,
    game_time: f64,
    map: []const u8,
    attacker_name: []const u8,
    attacker_uid: []const u8,
    attacker_weapon: []const u8,
    attacker_titan: []const u8,
    attacker_x: f64,
    attacker_y: f64,
    attacker_z: f64,
    victim_name: []const u8,
    victim_uid: []const u8,
    victim_weapon: []const u8,
    victim_titan: []const u8,
    victim_x: f64,
    victim_y: f64,
    victim_z: f64,
    cause_of_death: []const u8,
    distance: f64,
};

pub const Filters = struct {
    page: ?[]const u8 = null,
    weapon: ?[]const u8 = null,
    server: ?[]const u8 = null,
};
